auto:	          true

markdown:         rdiscount
pygments:         true
paginate:         6
permalink:        /:title

title:            softlightblog.me
url:              http://softlightblog.me
feed:             /atom.xml
author:
    name:         softlight
description:      "softlight\'s Blog"