auto:          true

pygments:      true
markdown:      rdiscount
paginate:      6
permalink:     /:title

title:         softlightblog.me
url:           http://softlightblog.me
author:
   name:       softlight
description:   "softlight\'s blog"